### ISSUE TITLE
examples checklist

### ISSUE THREAD

**Issue by lambtron** [denoland/examples#1]
each example must include:

- [ ] routing
- [ ] dynamic routes
- [ ] components
- [ ] no build step (if possible)
- [ ] high level overview with links in the index 
- [ ] readme with high level overview, links
- [ ] deploy to...
  - [ ] deno
  - [ ] netlify
  - [ ] vercel
  - [ ] cloudflare workers?
